# Conda environment for Gammapy version 1.1
# Install:    conda env create -f gammapy-1.1-environment.yml
# Activate:   conda activate gammapy-1.1
# Deactivate: conda deactivate

name: gammapy-1.1

channels:
  - conda-forge
  - sherpa

variables:
  PYTHONNOUSERSITE: "1"

dependencies:
  - python=3.9
  - gammapy=1.1
  - ipython=8.7.0
  - cython
  - jupyter
  - jupyterlab=3.5
  - pyyaml=6.0
  - click=8.1.3
  - numpy=1.24
  - scipy=1.10.1
  - pandas=1.5.2
  - matplotlib=3.7
  - astropy=5.3
  - regions=0.7
  - iminuit=2.21
  - sherpa=4.15
  - healpy=1.16
  - naima=0.10
  - pydantic=1.9
  - emcee=3.1.3
  - corner=2.2.1
  - pip
  - requests
  - tqdm


    